# Generated by Django 5.0.2 on 2024-04-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_exp',
            field=models.CharField(default='', help_text='Format: MM/YY', max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], default='delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='card', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_first',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_last',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_middle',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_state',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_zip',
            field=models.IntegerField(default=0),
        ),
    ]
