# Generated by Django 5.0.2 on 2024-04-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_order_card_exp_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_cvv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.IntegerField(default=0),
        ),
    ]
