# Generated by Django 5.0.2 on 2024-05-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_order_card_cvv_order_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_exp',
            field=models.CharField(blank=True, default='', help_text='Format: MM/YY', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_middle',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
