# Generated by Django 5.0.2 on 2024-05-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_alter_order_card_exp_alter_order_recipient_middle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_exp',
            field=models.CharField(default='', help_text='Format: MM/YY', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_middle',
            field=models.CharField(default='', max_length=20),
        ),
    ]
