# Generated by Django 5.0.2 on 2024-05-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0009_alter_order_card_exp_alter_order_recipient_middle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_exp',
        ),
    ]
