# Generated by Django 5.0.2 on 2024-05-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0010_remove_order_card_cvv_remove_order_card_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
