# Generated by Django 5.0.2 on 2024-05-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0012_alter_order_recipient_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recipient_zip',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
